### ISSUE TITLE
Restrict the origins the MediaHandler passes the authorization header to

### ISSUE THREAD

**Issue by Buuhuu** [adobe/helix-html2md#268]
**Description**
html2md accepts an authorization header, which is passed-through the MediaHandler to fetch all the images in a document and upload them to the media bus. This is not limited to the trusted origin the authorization header is meant to be used for. 

This could eventually be misused to obtain the authorization header by adding an image hosted on a 3rd-party origin that can log the authorization header. If the system that integrates that way uses a service user and sends the according authorization header it may allow an author to escalate permissions.   

**To Reproduce**
1. Create a service that hosts an image and logs all http headers
2. Add a reference to the image to a the document being fetched by html2md
3. Call html2md with an authorization header
4. See the header being logged in the 3rd-party service

**Expected behavior**
The authorization token should only be passed-through to trusted origins, e.g. only to the same-origin as in the fstab.yaml. Ideally we could add other origins we own and know are secure (like AEM CS, Dynamic Media, Polaris).  

Alternatively we could skip loading images into the media bus for assets hosted on Adobe's own image delivery infrastructures (like Dynamic Media or Polaris). In that case we would eventually have additional efforts when using the `createOptimizedImage()` boilerplate method - or at least this would mean some additional efforts in a project. 

Not sure what the right approach would be.

**Additional context**
With Crosswalk we aim to publish existing AEM content to the helix delivery infrastructure. To do so we use a serverless worker that transforms the markup rendered by AEM to html the html2md can work with. In the fstab.yaml we point to this serverless worker (aka converter). It would be possible to rewrite image references to point to the same origin (the converter) but that would mean we have to proxy the binaries as well. Ideally we could rewrite the images in a way that they are directly loaded from an AEM CS environment.

**Comment by tripodsan** [comment]
this should be controlled by a response header on the referrer html, eg: `x-html2md-media-src`

for example:

```
x-html2md-media-src: self; https://*.adobeaemcloud.com
```

**Comment by Buuhuu** [comment]
Currently the img-src policy controls which images we are pulled into media bus or not. 

We should always pull all images and the img-src policy should control to which origins we send credentials or not. 

Still we may need to send credentials to origins different to the one in fstab.yaml because in one variation of crosswalk we the fstab.yaml points to an aio runtime function but we don't want to proxy image binaries through runtime.

**Comment by tripodsan** [comment]
> img-src policy should control to which origins we send credentials or not.

...where the default should be to not include creds for different origins.
