### ISSUE TITLE
Add helix repo/owner/branch as headers to the requests made by html2md

### ISSUE THREAD

**Issue by Buuhuu** [adobe/helix-html2md#269]
**Is your feature request related to a problem? Please describe.**
With AEM we have a CMS that supports multiple sites per default. In franklin each repository maps to a single site. Accordingly we have to map the paths in AEM to something that is meaningful in Franklin, e.g.

/content/mysite/de-ch=> main--mysite-ch--myorg.hlx.page/de

The mapping can happen transparently in the service that interacts with the helix-admin api when publishing. However html2md will request the origin with the given path, e.g.

<origin>/de.html

It is possible to configure the the fstab.yaml in a way that it would prefix the path with a fix path, for example so that the request would become

<origin>/content/mysite/de.html

but that would still not work for the case given above. Also it would not help for content that is maintained at a different location like experience fragments (which we may need for the publication of existing AEM content). 

**Describe the solution you'd like**
The conclusion is that there needs to be a dispatcher that is able to map the incoming path to the actual location in AEM and forward the request. To implement that in a reusable way we could use a dispatcher servlet in AEM that finds the right location for a given request path, owner and repo. The latter information are currently not available in the requests made by html2md. 

The ask of this feature request is to add the repo/owner/branch (franklin coordinates) as header to the requests made by html2md.

**Describe alternatives you've considered**
We could implement the dispatcher as serverless worker on a project level and implement the mapping & forwarding there. But as this is something we need for all crosswalk customers the multi-tenant approach would be preferred.

**Comment by tripodsan** [comment]
> The ask of this feature request is to add the repo/owner/branch (franklin coordinates) as header to the requests made by html2md.

but the content is technically independent of the code repository. i.e. it is possible to have multiple code repositories using the same content. 

however, I see the use-case

**Comment by tmaret** [comment]
IIUC the proposed approach maps each path back and forth, when posting to Helix Admin API and when handling the get request from html2md. This double mapping could be a source of confusion and configuration issues. 

How about striving to apply the mapping only once and in AEM ? One way to do this would be for AEM to return a public path as a response header and html2md to honour that path when storing the content.

**Comment by tripodsan** [comment]
the problem is, that the imported content is stored relative to the `contentBusId`, which is basically a hash of the fstab root. this means, that even if we would send along the owner/repo information, the content would be imported to the same place.
you cannot have multiple projects pointing to the same fstab root.

**Comment by Buuhuu** [comment]
So for us something like https://author-pXYZ-eXZY.adobeaemcloud.com/franklin-site/<owner>/<repo>/<path> would be better, as this would be unique per repo and would also contain all the information we would need to dispatch it to the right content on AEM. I guess the contentBusId mechanism is nothing we can/want to change in order to make it unique per repo for this use case.

Returning the desired public path as response header from the content origin sounds reasonable to me, but is at least for me a source of confusion as well: I tell admin.hlx.page to preview `/content/site/foo/bar` and the preview url will be `/something-werid`. I could imaging that this would need some special handling in other places as well, like sidekick as well, if we intend to make use of it for xwalk. So having a consistent url space on hlx makes sense to me. Mapping and reverse-mapping should be dealt with by the content origin.

**Comment by tripodsan** [comment]
> Going off track: we haven't yet talked about much about preview, but I could imaging that we at some point will preview from AEM only,
I'd assume this is what you are doing...since the html2md import only happens on preview.

> and publish from hlx.page to live using the sidekick. In this case the sidekick will not know the original content path so we would have to apply the reverse mapping again somewhere.

why would it need the original content path? it would not be different than any other franklin project; it just copies the content from the preview to the live content partition in the content-bus.

**Comment by Buuhuu** [comment]
When we publish (from AEM Sites Admin or Universal Editor) we do a /preview and a /live API after each other. AEM also has a preview feature (separate agent) for which we would only do the /preview call and redirect the user to the hlx.page. 

My bad, you are right. For publish it would need to be the actual page `/something-weird`, so the problem would be with reload in the sidekick, no? We may not need this, idk  yet.
