### ISSUE TITLE
Better support for empty blocks.

### ISSUE THREAD

**Issue by mhaack** [adobe/helix-html2md#366]
Currently we need a workaround for empty block which have no block content and add an empty row.

**Today**
```
<div class="product-category">
  <div>
    <div></div>
  </div>
</div>
```

Works to create a block without any content.

**Expected**
```
<div class="product-category">
</div>
```

This pattern should be accepted as empty block with no content as well, additionally to today's behavior.

**Comment by Buuhuu** [comment]
What as implemented with https://github.com/adobe/helix-html2md/pull/367 was handling of 

```
<div class="block-name"><div>
```

Butt not the structure mentioned in the description.

Here is another structure that is not correctly processed:

```
<div class="block-name">

</div>
```
